spring.application.name=gateway-service
server.port=10241

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://admin:1234@team1-eureka:10233/eureka}

spring.cloud.compatibility-verifier.enabled=false

spring.rabbitmq.addresses=${MQ_ADDRESS}

spring.rabbitmq.username=${MQ_USER}
spring.rabbitmq.password=${MQ_PASSWORD}

mq.exchange.event=${MQ_EXCHANGE}
mq.routing-key.event=${MQ_ROUTING_KEY}

spring.profiles.active=dev