spring.application.name=gateway-service
server.port=10241

eureka.client.service-url.defaultZone=https://admin:1234@eureka.luckyseven.live/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.compatibility-verifier.enabled=false

spring.rabbitmq.addresses=s4.java21.net:5672

spring.rabbitmq.username=admin
spring.rabbitmq.password=nhnacademy123!

mq.exchange.event=event.exchange
mq.routing-key.event=event.routing

spring.profiles.active=test
